backend:
  name: git-gateway
  branch: main 

media_folder: "images/uploads" 

  - name: "blog" 
    label: "Blog Post" 
    folder: "_blogs"
    create: true
    slug: '{{title}}'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blogpost"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: Image, name: image, widget: image, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}

